# IMPORTANT: list items specified here is not possible to override as they
# appended during merging
{%- set nginx_ingress_namespace_class = "openstack-ingress-nginx" %}
{%- if OSVer[openstack_version] >= OSVer.yoga %}
  {%- set cirros_image_name = "Cirros-6.0" %}
  {%- set dhcp_client = "dhcpcd" %}
{%- else %}
  {%- set cirros_image_name = "Cirros-5.1" %}
{%- endif %}
internal_domain_name: cluster.local
common:
  charts:
    releases:
      namespace: {{ openstack_namespace }}
  openstack:
    values:
      network:
        api:
          ingress:
            classes:
              namespace: {{ nginx_ingress_namespace_class }}

features:
  logging:
    cadf:
      enabled: false
      driver: messagingv2
    cinder:
      level: DEBUG
    neutron:
      level: DEBUG
    nova:
      level: DEBUG
    octavia:
      level: DEBUG
  services:
    - block-storage
    - compute
    - dns
    - identity
    - dashboard
    - image
    - ingress
    - database
    - memcached
    - networking
    - orchestration
    - messaging
{%- if OSVer[openstack_version] >= OSVer.stein %}
    - placement
{%- endif %}
    - coordination
    - key-manager
    - load-balancer
    - redis
    - descheduler
    - dynamic-resource-balancer
  network_policies:
{%- if OSVer[openstack_version] >= OSVer.yoga %}
    enabled: true
{%- else %}
    enabled: false
{%- endif %}
  neutron:
    backend: tungstenfabric
  database:
    local_volumes:
      enabled: true
  ssl:
    public_endpoints:
      enabled: true
  stacklight:
    enabled: true
    user:
      username: stacklight
services:
  ingress:
    ingress:
      values:
        deployment:
          # NOTE(vsaienko): deploy in cluster mode to allow handle ingress'es
          # from TF namespace
          mode: "cluster"
          cluster:
            class: {{ nginx_ingress_namespace_class }}
  database:
    mariadb:
      values:
        conf:
          database_conf:
            mysqld:
              wsrep_provider_options:
                gcache.size: 1024M
  dashboard:
    horizon:
      values:
        {%- if OSVer[openstack_version] <= OSVer.queens %}
        conf:
          horizon:
            local_settings:
              config:
                tungstenfabric:
                  dashboard_name: contrail_openstack_dashboard.overrides
        {%- endif %}
        {%- if OSVer[openstack_version] >= OSVer.antelope %}
        conf:
          policy.d:
            nova:
              01-controller-default.yaml:
                "os_compute_api:os-migrate-server:migrate": "rule:project_member_or_admin"
                "os_compute_api:os-migrate-server:migrate_live": "rule:project_member_or_admin"
        {%- endif %}
        network:
          dashboard:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
  networking:
    neutron:
      values:
        network:
          server:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
        {%- if OSVer[openstack_version] <= OSVer.rocky %}
        conf:
          DEFAULT:
            api_extensions_path: 'extensions:/var/lib/openstack/lib/python2.7/site-packages/neutron_plugin_contrail/extensions'
        {%- endif %}
  orchestration:
    heat:
      values:
        network:
          cfn:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
          cloudwatch:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
  compute:
    nova:
      values:
        conf:
          {%- if OSVer[openstack_version] >= OSVer.antelope %}
          policy.d:
            01-controller-default.yaml:
              "os_compute_api:os-migrate-server:migrate": "rule:project_member_or_admin"
              "os_compute_api:os-migrate-server:migrate_live": "rule:project_member_or_admin"
          {%- endif %}
          nova:
            filter_scheduler:
              enabled_filters:
              - AggregateInstanceExtraSpecsFilter
              # - AggregateImagePropertiesIsolation
              # - AggregateIoOpsFilter
              # - AggregateMultiTenancyIsolation
              # - AggregateNumInstancesFilter
              - AggregateTypeAffinityFilter
              # - AllHostsFilter
              {%- if OSVer[openstack_version] <= OSVer.caracal %}
              - AvailabilityZoneFilter
              {%- endif %}
              - ComputeFilter
              - ComputeCapabilitiesFilter
              - DifferentHostFilter
              - ImagePropertiesFilter
              - IsolatedHostsFilter
              # - IoOpsFilter
              # - MetricsFilter
              - SameHostFilter
              - ServerGroupAntiAffinityFilter
              - ServerGroupAffinityFilter
              - SimpleCIDRAffinityFilter
              - NUMATopologyFilter
              # - NumInstancesFilter
              - PciPassthroughFilter
            libvirt:
            {%- if OSVer[openstack_version] <= OSVer.ussuri %}
              live_migration_use_ip_to_scp_configdrive: true
            {%- else %}
              migrations_use_ip_to_scp: true
            {%- endif %}
          enable_iscsi: true
        network:
          api:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
          metadata:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
          osapi:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
          placement:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
          novncproxy:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
          spiceproxy:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
          serialproxy:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
        bootstrap:
          structured:
            flavors:
              options:
                m1.extra_tiny_test:
                  disk: 5
                  name: m1.extra_tiny_test
                  ram: 256
                  vcpus: 1
                m1.tiny_test:
                  disk: 5
                  name: m1.tiny_test
                  ram: 512
                  vcpus: 1
  metric:
    gnocchi:
      values:
        network:
          api:
            ingress:
              classes:
                namespace: {{ nginx_ingress_namespace_class }}
  tempest:
    tempest:
      values:
        conf:
          # NOTE(vsaienko): disable cleanup explicitly to avoid production data loss.
          # DANGER: do not enable this on production environment.
          cleanup:
            enabled: False
          convert_to_uuid:
            compute:
              image_ref: {{ cirros_image_name }}
              image_ref_alt: {{ cirros_image_name ~ '.alt' }}
              image_raw_ref: {{ cirros_image_name ~ '.raw' }}
              flavor_ref:  m1.extra_tiny_test
              flavor_ref_alt: m1.tiny_test
          blacklist:
            # Skip unsupported Tungsenfabric tests
            # TODO(vsaienko): remove when PRODX-3721 resolved.
            - (?:tempest.api.network.test_subnetpools_extensions.SubnetPoolsTestJSON)
            - (?:neutron_tempest_plugin.api.test_subnetpool_prefix_ops)
            - (?:neutron_tempest_plugin.api.test_subnetpools)
            - (?:neutron_tempest_plugin.api.test_subnetpools_negative)
            # TODO(ibumarskov): not supported by TF (PRODX-4410)
            - (?:tempest.api.network.test_networks.Networks(|IpV6)Test.test_update_subnet_gw_dns_host_routes_dhcp)
            # TODO(ibumarskov): not supported by TF (PRODX-5181)
            - (?:neutron_tempest_plugin.scenario.test_connectivity.NetworkConnectivityTest.test_connectivity_through_2_routers)
            # TODO(ibumarskov): not supported by TF (PRODX-4831)
            - (?:neutron_tempest_plugin.api.admin.test_ports.PortTestCasesAdmin.test_update_mac_address)
            # Not supported by TF (PRODX-36749)
            - (?:neutron_tempest_plugin.scenario.test_security_groups.StatefulNetworkSecGroupTest.test_default_sec_grp_scenarios)
            # TODO(ibumarskov): not supported by TF (PRODX-5284)
            - (?:heat_tempest_plugin.tests.functional.test_create_update_neutron_subnet.UpdateSubnetTest.test_update_gateway_ip)
            - (?:heat_tempest_plugin.tests.functional.test_create_update_neutron_subnet.UpdateSubnetTest.test_update_gateway_ip_to_empty)
            - (?:heat_tempest_plugin.tests.functional.test_create_update_neutron_subnet.UpdateSubnetTest.test_update_to_no_gateway_ip)
            # Not supported by TF (PRODX-21320)
            - (?:heat_tempest_plugin.tests.functional.test_create_update_neutron_trunk.UpdateTrunkTest.test_update_trunk_name_and_description)
            # TODO(ibumarskov): not supported by TF (PRODX-5188)
            - (?:tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops)
            - (?:neutron_tempest_plugin.scenario.test_floatingip.DefaultSnatToExternal.test_snat_external_ip)
            # TODO(ibumarskov): not supported by TF (PRODX-5252)
            - (?:tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_port_security_macspoofing_port)
            # not supported by TF (PRODX-4801)
            - (?:neutron_tempest_plugin.api.admin.test_floating_ips_admin_actions.FloatingIPAdminTestJSON.test_create_floatingip_with_specified_ip_address)
            # Not supported by TF (PRODX-26371)
            - (?:octavia_tempest_plugin.tests.scenario.v2.test_traffic_ops.TrafficOperationsScenarioTest.test_insert_headers)
            # Skip SoftwareConfigIntegrationTest because it requires a custom image
            # https://github.com/openstack/heat/blob/stable/train/heat_integrationtests/prepare_test_env.sh
            - (?:heat_tempest_plugin.tests.scenario.test_server_software_config.SoftwareConfigIntegrationTest)
            # The test below is skipped while upstream bug (https://bugs.launchpad.net/tempest/+bug/1317133) is not fixed.
            - (?:tempest.api.object_storage.test_container_sync_middleware.ContainerSyncMiddlewareTest.test_container_synchronization)
            # Do not run test that plays plugs real computes to agregates on the fly, dengerous for production PRODX-14770
            - (?:tempest.scenario.test_aggregates_basic_ops.TestAggregatesBasicOps.test_aggregate_basic_ops)
          {%- if signature_enabled %}
            # Skip TEST failed, that doesn't work with static accounts correctly
            # TODO(vsaienko): remove when PRODX-18761 is fixed
            - (?:tempest.api.compute.servers.test_server_actions.ServerActionsTestJSON.test_shelve_unshelve_server)
            - (?:tempest.api.compute.servers.test_servers_negative.ServersNegativeTestJSON.test_shelve_shelved_server)
            - (?:tempest.scenario.test_shelve_instance.TestShelveInstance.test_shelve_instance)
            # TODO(vsaienko): remove when PRODX-18763 is fixed
            - (?:neutron_tempest_plugin.api.admin.test_networks.NetworksTestAdmin.test_create_network_with_project)
            - (?:neutron_tempest_plugin.api.admin.test_networks.NetworksTestAdmin.test_create_network_with_project_and_tenant)
            - (?:neutron_tempest_plugin.api.test_security_groups.SecGroupQuotaTest.test_create_sg_when_quota_disabled)
            - (?:neutron_tempest_plugin.api.test_security_groups.SecGroupRulesQuotaTest.test_create_sg_rules_when_quota_disabled)
            - (?:neutron_tempest_plugin.api.test_security_groups.SecGroupTest.test_list_security_group_rules_contains_all_rules)
            - (?:neutron_tempest_plugin.api.test_security_groups_negative.NegativeSecGroupQuotaTest.test_create_excess_sg)
            - (?:neutron_tempest_plugin.api.test_security_groups_negative.NegativeSecGroupRulesQuotaTest.test_sg_creation_with_insufficient_sg_rules_quota)
            # Skip TESTs failed, that don't work with signature verification enabled
            - (?:tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario)
            - (?:tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_instance_hard_reboot_after_vol_snap_deletion)
            - (?:tempest.scenario.test_snapshot_pattern.TestSnapshotPattern.test_snapshot_pattern)
            - (?:tempest.scenario.test_stamp_pattern.TestStampPattern.test_stamp_pattern)
            # TODO: enable this test, needs a barbican secret with clouds.yaml for 'another cloud', can reuse ourselves, may be with different account.
            - (?:heat_tempest_plugin.tests.functional.test_remote_stack.RemoteStackTest.test_stack_create_with_cloud_credential)
            # SKIPPED: tempest provides user and admin accounts for test from different projects (bug PRODX-28267)
            # can be unskipped when both accounts will be provided from the same project
            - (?:tempest.api.compute.admin.test_live_migration.LiveAutoBlockMigrationV225Test.test_volume_backed_live_migration)
            - (?:tempest.api.compute.admin.test_live_migration.LiveMigrationTest.test_volume_backed_live_migration)
          {%- endif %}
          {%- if OSVer[openstack_version] >= OSVer.yoga %}
            - (?:tempest.api.image.v2.test_images.ImportImagesTest.test_image_glance_direct_import)
          {%- endif %}
            # Tests NOT supported by product
{% include 'base/_tempest_blacklist_no_supported.yaml' %}
          script: |
            tempest run --config-file /etc/tempest/tempest.conf -w 4 --smoke --blacklist-file  /etc/tempest/test-blacklist
          tempest:
            DEFAULT:
              production: true
            dns:
              tld_suffix: test
              build_timeout: 600
            patrole:
              custom_policy_files: /etc/tempest/policies/%s.json
            sdn:
              service_name: tungstenfabric
              catalog_type: sdn
              endpoint_type: internal
            heat_plugin:
              image_ref: Fedora-27-1.6
              instance_type: m1.tiny_test
              minimal_image_ref: {{ cirros_image_name }}
              minimal_instance_type: m1.extra_tiny_test
            identity:
              ca_certificates_file: /certs/ca-bundle.pem
            volume:
              build_timeout: 600
            #TODO(mshalamov): Will be removed during process of completing PRODX-1192
            compute:
              fixed_network_name: tempest-fixed-net
              build_timeout: 600
            # NOTE(vsaienko): let nova scheduler pick destination host
            compute-feature-enabled:
              can_migrate_between_any_hosts: false
            {%- if OSVer[openstack_version] >= OSVer.antelope %}
              cold_migration_nonadmins: true
              live_migration_nonadmins: true
            {%- endif %}
            #TODO(mshalamov): Will be removed during process of completing PRODX-1192
            image:
              build_timeout: 600
            load_balancer:
              lb_build_timeout: 1500
              build_timeout: 600
              listener_conn_limit: 50000
            validation:
              image_ssh_password: gocubsgo
              image_ssh_user: cirros
              image_alt_ssh_password: gocubsgo
              image_alt_ssh_user: cirros
            network:
              shared_physical_network: false
              floating_network_name: public
              #TODO(ibumarskov): limitation from commit of https://bugs.launchpad.net/juniperopenstack/+bug/1720118
              project_network_cidr: 10.100.0.0/24
              project_network_v6_cidr: 2003::/120
              project_network_v6_mask_bits: 124
            network-feature-enabled:
              #TODO(ibumarskov): feature not implemented https://bugs.launchpad.net/juniperopenstack/+bug/1604568
              ipv6_subnet_attributes: false
            volume-feature-enabled:
              api_v1: false
              api_v2: false
              api_v3: true
              cluster_active_active: true
            telemetry:
              disable_ssl_certificate_validation: true
            image-feature-enabled:
              enabled_import_methods: 'web-download,glance-direct,copy-image'
            service-clients:
              http_timeout: 120
            {%- if dhcp_client is defined %}
            scenario:
              dhcp_client: {{ dhcp_client }}
            {%- endif %}
          tempest_logging:
            handler_file:
              args: ('/var/lib/tempest/data/tempest.log',)
              class: FileHandler
              formatter: tests
              level: DEBUG
            handler_stdout:
              level: WARN
            handlers:
              keys: file,stdout
            logger_root:
              handlers: stdout,file
              level: DEBUG
            logger_tempest:
              handlers: stdout,file
              level: DEBUG

        manifests:
          job_bootstrap: true
  identity:
    keystone:
      values:
        endpoints:
          identity:
            auth:
              osctl:
                role: admin,global-secret-decoder
  key-manager:
    barbican:
      values:
        conf:
          policy.d:
            01-controller-default.yaml:
            {%- if OSVer[openstack_version] >= OSVer.stein %}
              # TODO(vsaienko): drop policy settings in upstream values.yaml to ensure in-code policy
              # defaults are used.
              secret_project_match: project_id:%(target.secret.project_id)s
              secret_creator_user: user_id:%(target.secret.creator_id)s
              container_project_match: project_id:%(target.container.project_id)s
              container_creator_user: user_id:%(target.container.creator_id)s
            {%- else %}
              secret_project_match: project:%(target.secret.project_id)s
              secret_creator_user: user:%(target.secret.creator_id)s
              container_project_match: project:%(target.container.project_id)s
              container_creator_user: user:%(target.container.creator_id)s
            {%- endif %}
              'secret:get': >-
                rule:secret_non_private_read or rule:secret_project_creator or
                rule:secret_project_admin or rule:secret_acl_read or
                role:global-secret-decoder
              'secret:decrypt': >-
                rule:secret_decrypt_non_private_read or rule:secret_project_creator or
                rule:secret_project_admin or rule:secret_acl_read or
                role:global-secret-decoder
            {%- if OSVer[openstack_version] <= OSVer.stein %}
              'order:delete': rule:admin_or_creator
            {%- elif OSVer[openstack_version] <= OSVer.victoria %}
              'order:delete': rule:admin_or_creator and project_id:%(target.order.project_id)s
            {%- else %}
              # TODO(pas-ha): re-check validity for 2023.1
              'order:delete': >-
                rule:admin_or_creator and rule:order_project_match or
                True:%(enforce_new_defaults)s and rule:order_project_member
            {%- endif %}
