{{/*
Copyright 2019 Wind River Systems, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- define "evaluatorProbeTemplate" }}
{{- $probeType := . }}
exec:
  command:
    - python
    - /tmp/health-probe.py
    - --config-file
    - /etc/aodh/aodh.conf
    - --process-name
    - aodh-evaluator
    - --probe-type
    - {{ $probeType }}
    - --check
    - database_sockets
{{- end }}


{{- if .Values.manifests.deployment_evaluator }}
{{- $envAll := . }}

{{- $mounts_aodh_evaluator := .Values.pod.mounts.aodh_evaluator.aodh_evaluator }}
{{- $mounts_aodh_evaluator_init := .Values.pod.mounts.aodh_evaluator.init_container }}

{{- $serviceAccountName := "aodh-evaluator" }}
{{ tuple $envAll "evaluator" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aodh-evaluator
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{ tuple $envAll "aodh" "evaluator" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  replicas: {{ .Values.pod.replicas.evaluator }}
  selector:
    matchLabels:
{{ tuple $envAll "aodh" "evaluator" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "aodh" "evaluator" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
        endpoints-hash: {{ .Values.endpoints | include "helm-toolkit.utils.get_hash" }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
{{ dict "envAll" $envAll "application" "aodh" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      affinity:
{{ tuple $envAll "aodh" "evaluator" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      nodeSelector:
        {{ .Values.labels.evaluator.node_selector_key }}: {{ .Values.labels.evaluator.node_selector_value }}
      initContainers:
{{ tuple $envAll "evaluator" $mounts_aodh_evaluator_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: aodh-evaluator
{{ tuple $envAll "aodh_evaluator" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.evaluator | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "aodh" "container" "aodh_evaluator" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
{{ dict "envAll" $envAll "component" "evaluator" "container" "evaluator" "type" "liveness" "probeTemplate" (include "evaluatorProbeTemplate" "liveness" | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
{{ dict "envAll" $envAll "component" "evaluator" "container" "evaluator" "type" "readiness" "probeTemplate" (include "evaluatorProbeTemplate" "readiness" | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
          command:
            - /tmp/aodh-evaluator.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/aodh-evaluator.sh
                  - stop
          volumeMounts:
{{ dict "envAll" $envAll "objectType" "mountpoint" "secretPrefix" "aodh" | include "helm-toolkit.snippets.kubernetes_ssl_objects" | indent 12 }}
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-etc-aodh
              mountPath: /etc/aodh
            - name: aodh-etc
              mountPath: /etc/aodh/aodh.conf
              subPath: aodh.conf
              readOnly: true
            {{- if .Values.conf.aodh.DEFAULT.log_config_append }}
            - name: aodh-etc
              mountPath: {{ .Values.conf.aodh.DEFAULT.log_config_append }}
              subPath: {{ base .Values.conf.aodh.DEFAULT.log_config_append }}
              readOnly: true
            {{- end }}
            - name: aodh-bin
              mountPath: /tmp/aodh-evaluator.sh
              subPath: aodh-evaluator.sh
              readOnly: true
            - name: aodh-bin
              mountPath: /tmp/health-probe.py
              subPath: health-probe.py
              readOnly: true
{{ if $mounts_aodh_evaluator.volumeMounts }}{{ toYaml $mounts_aodh_evaluator.volumeMounts | indent 12 }}{{ end }}
      volumes:
{{ dict "envAll" $envAll "objectType" "volume" "secretPrefix" "aodh" | include "helm-toolkit.snippets.kubernetes_ssl_objects" | indent 8 }}
        - name: pod-tmp
          emptyDir: {}
        - name: pod-etc-aodh
          emptyDir: {}
        - name: aodh-etc
          secret:
            secretName: aodh-etc
            defaultMode: 416
        - name: aodh-bin
          configMap:
            name: aodh-bin
            defaultMode: 504
{{ if $mounts_aodh_evaluator.volumes }}{{ toYaml $mounts_aodh_evaluator.volumes | indent 8 }}{{ end }}
{{- end }}
