{{/*
Copyright 2019 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.configmap_etc }}
{{- $envAll := . }}

{{- if empty .Values.conf.stepler_env.OS_USERNAME -}}
{{- $_ := set .Values.conf.stepler_env "OS_USERNAME" .Values.endpoints.identity.auth.stepler.username -}}
{{- end -}}
{{- if empty .Values.conf.stepler_env.OS_PASSWORD -}}
{{- $_ := set .Values.conf.stepler_env "OS_PASSWORD" .Values.endpoints.identity.auth.stepler.password -}}
{{- end -}}
{{- if empty .Values.conf.stepler_env.OS_PROJECT_NAME -}}
{{- $_ := set .Values.conf.stepler_env "OS_PROJECT_NAME" .Values.endpoints.identity.auth.stepler.project_name -}}
{{- end -}}
{{- if empty .Values.conf.stepler_env.OS_PROJECT_DOMAIN_NAME -}}
{{- $_ := set .Values.conf.stepler_env "OS_PROJECT_DOMAIN_NAME" .Values.endpoints.identity.auth.stepler.project_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.stepler_env.OS_REGION_NAME -}}
{{- $_ := set .Values.conf.stepler_env "OS_REGION_NAME" .Values.endpoints.identity.auth.stepler.region_name -}}
{{- end -}}
{{- if empty .Values.conf.stepler_env.OS_USER_DOMAIN_NAME -}}
{{- $_ := set .Values.conf.stepler_env "OS_USER_DOMAIN_NAME" .Values.endpoints.identity.auth.stepler.user_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.stepler_env.OS_AUTH_URL -}}
{{- $_ := tuple "identity" "public" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.stepler_env "OS_AUTH_URL" -}}
{{- end -}}

{{- if empty .Values.conf.stepler_env.OS_DASHBOARD_URL -}}
{{- $endpointScheme := tuple "dashboard" "public" "web" . | include "helm-toolkit.endpoints.keystone_endpoint_scheme_lookup" }}
{{- $endpointHost := tuple "dashboard" "public" . | include "helm-toolkit.endpoints.endpoint_host_lookup" }}
{{- $endpointPort := tuple "dashboard" "public" "web" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{- $endpointPath := tuple "dashboard" "public" "web" . | include "helm-toolkit.endpoints.keystone_endpoint_path_lookup" }}
    # When CSRF protection is enabled Refferer and Host header should match.
    # Common browsers doesn't add default ports like 80 and 443 to the headers
    # Use the same logic here to make sure test passed when CSRF protection is enabled and
    # we using default port numbers. More info may be found here:
    # * https://code.djangoproject.com/ticket/26037
    # * https://stackoverflow.com/questions/27533011/django-csrf-error-casused-by-nginx-x-forwarded-host
    {{- if eq $endpointPort "80" "443" }}
        {{- printf "%s://%s%s" $endpointScheme $endpointHost $endpointPath | set .Values.conf.stepler_env "OS_DASHBOARD_URL" }}
    {{- else }}
        {{- printf "%s://%s:%s%s" $endpointScheme $endpointHost $endpointPort $endpointPath | set .Values.conf.stepler_env "OS_DASHBOARD_URL" }}
    {{- end }}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: stepler-etc
type: Opaque
data:
  stepler-env.conf: {{ include "helm-toolkit.utils.to_env_conf" .Values.conf.stepler_env | b64enc }}
{{- end }}
