site_name: Rockoon Kubernetes OpenStack Operator
site_author: Mirantis
docs_dir: ./docs
repo_name: GitHub
repo_url: https://github.com/mirantis/rockoon
copyright:
  '© 2005 - 2024 Mirantis, Inc. All rights reserved.'
theme:
  name: "material"
  font:
    text: Overpass
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  icon: assets/mirantis-logo-inverted-horizontal-one-color.svg
  logo: assets/mirantis-logo-inverted-horizontal-one-color.svg
  favicon: assets/favicon.ico

  search: true
  search_index_only: true
  features:
    - toc.autohide
    - search.suggest
    - search.highlight
    # - navigation.sections
    # - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.path
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mermaid2
  - callouts

#extra:
#  generator: false

# Page tree

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 3
nav:
  - Home: index.md
  - Architecture:
    - Rockoon Operator:
      - Deployment Overview: architecture/rockoon/overview.md
      - Configuration: architecture/rockoon/configuration.md
      - Custom Images: architecture/rockoon/custom-images.md
    - Rockoon Admission: architecture/rockoon-admission.md
    - Custom Resources:
      - OpenStackDeployment: architecture/custom-resources/openstackdeployment.md
      - OpenStackDeploymentStatus: architecture/custom-resources/openstackdeploymentstatus.md
    - Cloud Services:
      - Horizon: architecture/cloud_services/horizon.md
      - Masakari: architecture/cloud_services/masakari.md
  - Quick Start:
    - AIO Installation:
      - Introduction: quick-start/introduction.md
      - TryMOSK (using pre-built image):
        - Installation on AWS: quick-start/trymosk-installation-aws.md
      - Manual install (Advanced): quick-start/aio-installation-manual.md
    - Access to AIO environment:
      - Configuring VPN: quick-start/vpn-config.md
      - Local clients configuration: quick-start/local-clients.md
  - Developer Guide: developer.md
  - Operations Guide:
    - Getting access to OpenStack: ops/openstack/getting-access.md
    - Upgrade OpenStack: ops/openstack/upgrade.md
    - Run tempest: ops/openstack/tempest.md
  - User Guide:
    - Instance HA:
      - Configure OpenStack with Masakari: user-guide/openstack/masakari/masakari-configuration.md
      - Introspective monitor test: user-guide/openstack/masakari/introspective-monitor.md
  - Troubleshoot: ops/openstack/troubleshoot.md
