- name: Providing info of the deployment
  hosts: k8s_controllers[0]
  become: true
  become_user: root
  tasks:
  - name: Getting info of the deployment
    include_role:
      name: rvl
      tasks_from: deployment-info.yaml