---
- name: Deploy initial controllers
  hosts: k8s_controllers[0]
  become: true
  become_user: root
  pre_tasks:
    - name: Set node role fact
      set_fact:
        rvl_controller_node: "{%- if ansible_hostname in groups.controllers %}True{%- endif %}"
        rvl_compute_node: "{%- if ansible_hostname in groups.computes %}True{%- endif %}"
        rvl_resolved_ip_address: "{{ hostvars[groups.k8s_controllers[0]]['ansible_default_ipv4']['address'] }}"
      tags:
        - all
  tasks:
  - name: Setup openstack controller
    include_role:
      name: rvl
      tasks_from: rockoon
  - name: Setup osdpl
    include_role:
      name: rvl
      tasks_from: osdpl
    tags:
      - wait
  - name: Configure DNS service
    include_role:
      name: rvl
      tasks_from: dns
    tags:
      - dns
