{%- from 'macros/connections.j2' import from_pod_networks %}
{%- from 'macros/connections.j2' import from_namespaces %}
{%- set lma_ns_list = ["lma_deployment"] | namespaces  %}
{%- set mariadb_server = "database:mariadb:StatefulSet:mariadb-server" %}
        mariadb-server:
          spec:
            podSelector:
              matchLabels:
{{ service_childs[mariadb_server].get_pod_labels() | toyaml | indent(16, first=True) }}
            policyTypes:
            - Ingress
            ingress:
{{ network_policies["ingress"][mariadb_server] | toyaml | indent(14, first=True) }}
              - from:
{{ from_pod_networks(pod_networks, service_childs[mariadb_server].get_np_ports(["mysql"])) | indent(16) }}
              - from:
{{ from_namespaces(lma_ns_list, service_childs[mariadb_server].get_np_ports(["metrics"])) | indent(16) }}
