{{/*
Copyright 2020 Mirantis Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.job_powerdns_db_sync }}
{{- $envAll := . }}


{{- $serviceAccountName := "designate-powerdns-db-sync" }}
{{ tuple $envAll "db_sync" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $serviceAccountName }}
spec:
  backoffLimit: 20
  template:
    metadata:
      labels:
{{ tuple $envAll "designate" "powerdns-db-sync" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
{{ dict "envAll" $envAll "application" "powerdns_db_sync" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.job.node_selector_key }}: {{ .Values.labels.job.node_selector_value }}
      initContainers:
{{ tuple $envAll "powerdns_db_sync" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: designate-powerdns-db-sync
{{ tuple $envAll "powerdns_db_sync" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ dict "envAll" $envAll "application" "powerdns_db_sync" "container" "powerdns_db_sync" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.jobs.db_sync | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          command:
            - /tmp/powerdns-mysql-sync.sh
          volumeMounts:
            - name: designate-powerdns-bin
              mountPath: /tmp/powerdns-mysql-sync.sh
              subPath: powerdns-mysql-sync.sh
              readOnly: true
            - name: designate-powerdns-etc
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
              readOnly: true
      volumes:
        - name: designate-powerdns-bin
          configMap:
            name: designate-powerdns-bin
            defaultMode: 504
        - name: designate-powerdns-etc
          secret:
            secretName: designate-powerdns-etc
            defaultMode: 416
{{- end }}

