# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- define "powerdnsProbeTemplate" }}
tcpSocket:
  port: {{ tuple "powerdns" "internal" "powerdns_tcp" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{- end }}
{{- define "mdnsProbeTemplate" }}
tcpSocket:
  port: {{ tuple "mdns" "internal" "ipc" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{- end }}

{{- if .Values.manifests.statefulset_mdns }}

{{- $envAll := . }}
{{- $mounts_designate_mdns := .Values.pod.mounts.designate_mdns.designate_mdns }}
{{- $mounts_designate_mdns_init := .Values.pod.mounts.designate_mdns.init_container }}

{{- $serviceAccountName := "designate-mdns" }}
{{ tuple $envAll "mdns" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: designate-mdns
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{ tuple $envAll "designate" "mdns" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  replicas: {{ .Values.pod.replicas.mdns }}
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
{{ tuple $envAll "designate" "mdns" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_statefulset" | indent 2 }}
  serviceName: {{ tuple "mdns" "discovery" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
  template:
    metadata:
      labels:
{{ tuple $envAll "designate" "mdns" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
        endpoints-hash: {{ .Values.endpoints | include "helm-toolkit.utils.get_hash" }}
        {{- if .Values.manifests.designate_powerdns }}
        configmap-powerdns-bin-hash: {{ tuple "configmap-powerdns-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-powerdns-etc-hash: {{ tuple "configmap-powerdns-etc.yaml" . | include "helm-toolkit.utils.hash" }}
        {{- end }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
{{ dict "envAll" $envAll "application" "designate" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      affinity:
{{ tuple $envAll "designate" "mdns" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      nodeSelector:
        {{ .Values.labels.mdns.node_selector_key }}: {{ .Values.labels.mdns.node_selector_value }}
      terminationGracePeriodSeconds: {{ .Values.pod.lifecycle.termination_grace_period.mdns.timeout | default "30" }}
      initContainers:
{{ tuple $envAll "mdns" $mounts_designate_mdns_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        {{- if .Values.manifests.designate_powerdns }}
        - name: designate-powerdns
{{ tuple $envAll "powerdns" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.server | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "designate" "container" "designate_powerdns" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
{{ dict "envAll" $envAll "component" "powerdns" "container" "powerdns" "type" "readiness" "probeTemplate" (include "powerdnsProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | trim | indent 10 }}
{{ dict "envAll" $envAll "component" "powerdns" "container" "powerdns" "type" "liveness" "probeTemplate" (include "powerdnsProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | trim | indent 10 }}
          command:
            - pdns_server
          ports:
            - containerPort: {{ tuple "powerdns" "internal" "powerdns" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
              name: pdns-udp
              protocol: UDP
            - containerPort: {{ tuple "powerdns" "internal" "powerdns_tcp" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
              name: pdns-tcp
            - containerPort: {{ tuple "powerdns" "internal" "powerdns_api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
              name: pdns-api
          volumeMounts:
            - name: designate-powerdns-etc
              mountPath: /etc/pdns/conf.d/pdns.conf
              subPath: pdns.conf
              readOnly: true
            - name: run-pdns
              mountPath: {{ index $envAll.Values.conf.powerdns "socket-dir" }}
          {{- end }}
        - name: designate-mdns
{{ tuple $envAll "designate_mdns" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.mdns | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "designate" "container" "designate_mdns" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
{{ dict "envAll" $envAll "component" "mdns" "container" "mdns" "type" "readiness" "probeTemplate" (include "mdnsProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | trim | indent 10 }}
{{ dict "envAll" $envAll "component" "mdns" "container" "mdns" "type" "liveness" "probeTemplate" (include "mdnsProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | trim | indent 10 }}
          ports:
            - name: d-mdns
              containerPort: {{ tuple "mdns" "internal" "ipc" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
            - name: d-mdns-udp
              containerPort: {{ tuple "mdns" "internal" "ipc" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
              protocol: UDP
          command:
            - bash
            - /tmp/designate-mdns.sh
          volumeMounts:
{{ dict "envAll" $envAll "objectType" "mountpoint" "secretPrefix" "designate" | include "helm-toolkit.snippets.kubernetes_ssl_objects" | indent 12 }}
            - name: designate-bin
              mountPath: /tmp/designate-mdns.sh
              subPath: designate-mdns.sh
              readOnly: true
            - name: pod-etc-designate
              mountPath: /etc/designate
            - name: pod-var-cache-designate
              mountPath: /var/cache/designate
            - name: designate-etc
              mountPath: /etc/designate/designate.conf
              subPath: designate.conf
              readOnly: true
            - name: designate-etc
              mountPath: /etc/designate/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            {{- if .Values.conf.designate.DEFAULT.log_config_append }}
            - name: designate-etc
              mountPath: {{ .Values.conf.designate.DEFAULT.log_config_append }}
              subPath: {{ base .Values.conf.designate.DEFAULT.log_config_append }}
              readOnly: true
            {{- end }}
            - name: pod-tmp
              mountPath: /tmp
{{- if $mounts_designate_mdns.volumeMounts }}{{ toYaml $mounts_designate_mdns.volumeMounts | indent 12 }}{{ end }}
        - name: designate-worker
{{ tuple $envAll "designate_worker" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.worker | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "designate" "container" "designate_worker" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
{{ dict "envAll" $envAll "component" "mdns" "container" "worker" "type" "liveness" "probeTemplate" (include "designateWorkerLivenessProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
{{ dict "envAll" $envAll "component" "mdns" "container" "worker" "type" "readiness" "probeTemplate" (include "designateWorkerReadinessProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
          command:
            - bash
            - /tmp/designate-worker.sh
          volumeMounts:
{{ dict "envAll" $envAll "objectType" "mountpoint" "secretPrefix" "designate" | include "helm-toolkit.snippets.kubernetes_ssl_objects" | indent 12 }}
            - name: designate-bin
              mountPath: /tmp/designate-worker.sh
              subPath: designate-worker.sh
              readOnly: true
            - name: designate-bin
              mountPath: /tmp/health-probe.py
              subPath: health-probe.py
              readOnly: true
            - name: pod-etc-designate
              mountPath: /etc/designate
            - name: pod-var-cache-designate
              mountPath: /var/cache/designate
            - name: designate-etc
              mountPath: /etc/designate/designate.conf
              subPath: designate.conf
              readOnly: true
            - name: designate-etc
              mountPath: /etc/designate/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            {{- if .Values.conf.designate.DEFAULT.log_config_append }}
            - name: designate-etc
              mountPath: {{ .Values.conf.designate.DEFAULT.log_config_append }}
              subPath: {{ base .Values.conf.designate.DEFAULT.log_config_append }}
              readOnly: true
            {{- end }}
            - name: pod-tmp
              mountPath: /tmp
{{- if $mounts_designate_mdns.volumeMounts }}{{ toYaml $mounts_designate_mdns.volumeMounts | indent 12 }}{{ end }}
      volumes:
{{ dict "envAll" $envAll "objectType" "volume" "secretPrefix" "designate" | include "helm-toolkit.snippets.kubernetes_ssl_objects" | indent 8 }}
        - name: pod-etc-designate
          emptyDir: {}
        - name: pod-var-cache-designate
          emptyDir: {}
        - name: run-pdns
          emptyDir: {}
        - name: designate-bin
          configMap:
            name: designate-bin
            defaultMode: 504
        - name: designate-etc
          secret:
            secretName: designate-etc
            defaultMode: 416
        {{- if .Values.manifests.designate_powerdns }}
        - name: designate-powerdns-etc
          secret:
            secretName: designate-powerdns-etc
            defaultMode: 416
        {{- end }}
        - name: pod-tmp
          emptyDir: {}
{{- if $mounts_designate_mdns.volumes }}{{ toYaml $mounts_designate_mdns.volumes | indent 8 }}{{ end }}
{{- end }}
