#connection_recycle_time is set to 300sec in order not to hit into conntrack timeouts (PRODX-1179, PRODX-1170)
# Optimized for the following cloud configuration
# controllers: 3
# computes: <10
features:
  messaging:
    components_with_dedicated_messaging:
      - networking
services:
  redis:
    redisfailover:
      redis:
        replicas: 3
      sentinel:
        replicas: 3
  database:
    mariadb:
      values:
        pod:
          lifecycle:
            disruption_budget:
              mariadb:
                min_available: 2
        conf:
          ingress_conf:
            proxy-buffer-size: "20m"
            proxy-connect-timeout: "600"
          phy_backup:
            backup_timeout: 3600
        volume:
          phy_backup:
            size: "20Gi"
  ingress:
    ingress:
      values:
        pod:
          replicas:
            ingress: 3
  identity:
    keystone:
      values:
        pod:
          replicas:
            api: 3
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          keystone:
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  key-manager:
    barbican:
      values:
        conf:
          software:
            apache2:
              processes:
                api: 2
        pod:
          replicas:
            api: 3
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
  image:
    glance:
      values:
        pod:
          replicas:
            api: 3
            registry: 3
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
              registry:
                min_available: 2
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 0
        conf:
          glance:
            DEFAULT:
              workers: 2
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  compute:
    nova:
      values:
        pod:
          replicas:
            api_metadata: 3
            osapi: 3
            conductor: 3
            consoleauth: 3
            scheduler: 3
            novncproxy: 3
            spiceproxy: 3
            placement: 3
            # Byggy code, give up and use 1 instance
            compute_ironic: 1
          lifecycle:
            disruption_budget:
              metadata:
                min_available: 2
              placement:
                min_available: 2
              osapi:
                min_available: 2
            upgrades:
              daemonsets:
                pod_replacement_strategy: RollingUpdate
                compute:
                  # upgrade computes in butches with 10% of hosts from maximum
                  max_unavailable: 10%
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 0
        conf:
          software:
            apache2:
              processes:
                api: 2
                metadata: 2
          nova:
            DEFAULT:
              metadata_workers: 1
              osapi_compute_workers: 1
              block_device_allocate_retries: 600
              block_device_allocate_retries_interval: 10
              report_interval: 30
              service_down_time: 180
              rpc_response_timeout: 60
            api_database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            cell0_database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            placement_database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            conductor:
              workers: 1
            scheduler:
              workers: 1
            neutron:
              timeout: 300
            filter_scheduler:
              host_subset_size: 3
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  networking:
    neutron:
      values:
        pod:
          replicas:
            server: 3
          lifecycle:
            disruption_budget:
              server:
                min_available: 2
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
              daemonsets:
                pod_replacement_strategy: RollingUpdate
                dhcp_agent:
                  max_unavailable: 10%
                l3_agent:
                  pod_replacement_strategy: OnDelete
                lb_agent:
                  max_unavailable: 10%
                metadata_agent:
                  max_unavailable: 10%
                ovs_agent:
                  max_unavailable: 10%
                sriov_agent:
                  max_unavailable: 10%
                netns_cleanup_cron:
                  max_unavailable: 100%
        conf:
          neutron:
            DEFAULT:
              dhcp_lease_duration: 86400
              rpc_workers: 2
              api_workers: 2
              rpc_state_report_workers: 2
              agent_down_time: 95
              max_l3_agents_per_router: 2
              executor_thread_pool_size: 70
            agent:
              report_interval: 30
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 70
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
          plugins:
            ml2_conf:
              ml2_type_vxlan:
                vni_ranges: 1:1000
            openvswitch_agent:
              ovs:
                of_connect_timeout: 300
                of_inactivity_probe: 30
                of_request_timeout: 300
                ovsdb_timeout: 30
    openvswitch:
      values:
        pod:
          lifecycle:
            upgrades:
              daemonsets:
                ovn_controller:
                  enabled: true
                  pod_replacement_strategy: OnDelete
                  max_unavailable: 1
                ovs_vswitchd:
                  enabled: true
                  pod_replacement_strategy: OnDelete
                  max_unavailable: 1
  block-storage:
    cinder:
      values:
        pod:
          replicas:
            api: 3
            scheduler: 3
            volume: 3
            backup: 3
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          software:
            apache2:
              processes: 2
          cinder:
            DEFAULT:
              rpc_response_timeout: 3600
              osapi_volume_workers: 1
              backup_workers: 2
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  shared-file-system:
    manila:
      values:
        pod:
          replicas:
            api: 3
            scheduler: 3
            share: 3
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          software:
            apache2:
              processes: 2
          manila:
            DEFAULT:
              rpc_response_timeout: 3600
              osapi_share_workers: 3
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  orchestration:
    heat:
      values:
        pod:
          replicas:
            cfn: 3
            api: 3
            engine: 3
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
              cfn:
                min_available: 2
              cloudwatch:
                min_available: 2
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          heat:
            DEFAULT:
              rpc_response_timeout: 600
              num_engine_workers: 1
              max_resources_per_stack: '20000'
              max_template_size: '5440000'
              max_json_body_size: '10880000'
            heat_api:
              workers: 1
            heat_api_cfn:
              workers: 1
            heat_api_cloudwatch:
              workers: 1
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  placement:
    placement:
      values:
        conf:
          software:
            apache2:
              processes: 2
        pod:
          replicas:
            api: 3
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
  load-balancer:
    octavia:
      values:
        pod:
          replicas:
            api: 3
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 0
              daemonsets:
                pod_replacement_strategy: RollingUpdate
                health_manager:
                  max_unavailable: 10%
        conf:
          software:
            apache2:
              processes: 5
          octavia:
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            controller_worker:
              amp_active_retries: 100
              amp_active_wait_sec: 4
              workers: 1
            haproxy_amphora:
              connection_max_retries: 1500
              connection_retry_interval: 1
              rest_request_conn_timeout: 10
              rest_request_read_timeout: 120
            task_flow:
              engine: parallel
              max_workers: 4
            health_manager:
              health_update_threads: 2
              stats_update_threads: 2
            house_keeping:
              amphora_expiry_age: 3600
              load_balancer_expiry_age: 3600
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  dns:
    designate:
      values:
        pod:
          replicas:
            api: 3
            central: 3
            mdns: 3
            producer: 3
            sink: 3
            worker: 3
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
              central:
                min_available: 2
              mdns:
                min_available: 2
              worker:
                min_available: 2
              producer:
                min_available: 2
              sink:
                min_available: 2
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          software:
            apache2:
              processes:
                api: 4
          designate:
            service:api:
              workers: 4
            service:central:
              workers: 4
            service:mdns:
              workers: 4
            service:producer:
              workers: 4
            service:sink:
              workers: 4
            service:worker:
              workers: 4
  dashboard:
    horizon:
      values:
        pod:
          replicas:
            server: 2
          lifecycle:
            disruption_budget:
              horizon:
                min_available: 1
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          software:
            apache2:
              processes: 3
              threads: 10
  baremetal:
    ironic:
      values:
        pod:
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
          replicas:
            api: 3
            conductor: 3
        conf:
          ironic:
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
  alarming:
    aodh:
      values:
        pod:
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
          replicas:
            api: 3
            evaluator: 3
            listener: 3
            notifier: 3
        conf:
          aodh:
            database:
              connection_recycle_time: 300
              max_overflow: 30
              max_pool_size: 10
  metric:
    gnocchi:
      values:
        pod:
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
          replicas:
            api: 3
        conf:
          gnocchi:
            database:
              connection_recycle_time: 300
              max_overflow: 30
              max_pool_size: 10
          software:
            apache2:
              processes: 4
  event:
    panko:
      values:
        pod:
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
          replicas:
            api: 3
  metering:
    ceilometer:
      values:
        pod:
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
          replicas:
            central: 3
            collector: 3
            notification: 3
  tempest:
    tempest:
      values:
        conf:
          tempest:
            compute:
              min_compute_nodes: 2
  memcached:
    memcached:
      values:
        conf:
          memcached:
            max_connections: 16384
  instance-ha:
    masakari:
      values:
        pod:
          replicas:
            api: 3
            engine: 3
          lifecycle:
            disruption_budget:
              api:
                min_available: 2
              engine:
                min_available: 2

timeouts:
  application_readiness:
    mariadb:
      timeout: 2400
      delay: 15
    nova:
      timeout: 600
      delay: 10
    neutron:
      timeout: 600
      delay: 10
    openvswitch:
      timeout: 600
      delay: 10
