---
- name: Get image name
  set_fact:
    image_name: "{{ image_for_mirror | regex_replace('^.*?/(.*):.*$', '\\1') }}"

- name: Get image tag
  set_fact:
    image_tag: "{{ image_for_mirror | regex_replace('^.*:(.*)$', '\\1') }}"

- name: Get image`s metadata from local registry
  ansible.builtin.uri:
    url: "https://{{ rvl_registry_host }}/v2/{{ image_name }}/manifests/{{ image_tag }}"
    return_content: false
  ignore_errors: True
  register: check_local_registry_result

- name: "Pool the image {{ image_name }}:{{ image_tag }}"
  community.docker.docker_image_pull:
    name: "{{ image_for_mirror }}"
  when: check_local_registry_result.failed

- name: "Tag the image {{ image_name }}:{{ image_tag }}"
  community.docker.docker_image_tag:
    name: "{{ image_for_mirror }}"
    repository:
      - "{{ rvl_registry_host }}/{{ image_name }}:{{ image_tag }}"
  when: check_local_registry_result.failed

- name: "Push the image {{ image_name }}:{{ image_tag }}"
  community.docker.docker_image_push:
    name: "{{ rvl_registry_host }}/{{ image_name }}:{{ image_tag }}"
  when: check_local_registry_result.failed

- name: "Remove image {{ image_name }}:{{ image_tag }}"
  community.docker.docker_image_remove:
    name: "{{ item }}"
  loop:
    - "{{ rvl_registry_host }}/{{ image_name }}:{{ image_tag }}"
    - "{{ image_for_mirror }}"
  when: check_local_registry_result.failed
