{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- define "ovsvswitchlivenessProbeTemplate" }}
exec:
  command:
    - /usr/bin/ovs-appctl
    - bond/list
{{- end }}
{{- define "ovsvswitchreadinessProbeTemplate" }}
exec:
  command:
    - /tmp/vswitchd_readiness.sh
{{- end }}
{{- define "ovsdblivenessProbeTemplate" }}
exec:
  command:
    - /usr/bin/ovs-vsctl
    - show
{{- end }}
{{- define "ovsdbreadinessProbeTemplate" }}
exec:
  command:
    - /usr/bin/ovs-vsctl
    - list
    - Open_Vswitch
{{- end }}

{{- define "openvswitch.openvswitch-vswitchd.daemonset" }}
{{- $daemonset := index . 0 }}
{{- $configMapName := index . 1 }}
{{- $serviceAccountName := index . 2 }}
{{- $envAll := index . 3 }}
{{- with $envAll }}

{{- $openvswitchVswitchdImage := "openvswitch_vswitchd" }}
{{- if .Values.conf.ovs_dpdk.enabled }}
    {{- $openvswitchVswitchdImage = "openvswitch_vswitchd_dpdk" }}
{{- end }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $daemonset }}
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{ tuple $envAll "openvswitch" "openvswitch-vswitchd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  selector:
    matchLabels:
{{ tuple $envAll "openvswitch" "openvswitch-vswitchd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll "ovs_vswitchd" | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "openvswitch" "openvswitch-vswitchd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
{{ dict "envAll" $envAll "podName" "openvswitch-vswitchd" "containerNames" (list "openvswitch-vswitchd" "openvswitch-vswitchd-modules" "init") | include "helm-toolkit.snippets.kubernetes_mandatory_access_control_annotation" | indent 8 }}
    spec:
      shareProcessNamespace: true
      serviceAccountName: {{ $serviceAccountName }}
{{ dict "envAll" $envAll "application" "openvswitch_vswitchd" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      nodeSelector:
        {{ .Values.labels.ovs.node_selector_key }}: {{ .Values.labels.ovs.node_selector_value }}
      dnsPolicy: {{ .Values.pod.dns_policy }}
      hostNetwork: true
      initContainers:
{{ tuple $envAll "vswitchd" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: openvswitch-vswitchd-modules
{{ tuple $envAll $openvswitchVswitchdImage | include "helm-toolkit.snippets.image" | indent 10 }}
{{ dict "envAll" $envAll "application" "openvswitch_vswitchd" "container" "modules" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          command:
            - /tmp/openvswitch-vswitchd-init-modules.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: openvswitch-bin
              mountPath: /tmp/openvswitch-vswitchd-init-modules.sh
              subPath: openvswitch-vswitchd-init-modules.sh
              readOnly: true
            - name: host-rootfs
              mountPath: /mnt/host-rootfs
              readOnly: true
              mountPropagation: HostToContainer
        - name: openvswitch-db-perms
{{ tuple $envAll "openvswitch_db_server" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ dict "envAll" $envAll "application" "openvswitch_vswitchd" "container" "perms" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.ovs.db | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          command:
            - chown
            - -R
            - {{ $envAll.Values.pod.security_context.openvswitch_vswitchd.container.db.runAsUser | quote }}
            - /run/openvswitch
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: run-openvswitch
              mountPath: /run/openvswitch
      containers:
        - name: openvswitch-db
{{ tuple $envAll "openvswitch_db_server" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ dict "envAll" $envAll "application" "openvswitch_vswitchd" "container" "db" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.ovs.db | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "component" "ovs_vswitchd" "container" "ovs_db" "type" "liveness" "probeTemplate" (include "ovsdblivenessProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
{{ dict "envAll" $envAll "component" "ovs_vswitchd" "container" "ovs_db" "type" "readiness" "probeTemplate" (include "ovsdbreadinessProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
          command:
            - /tmp/openvswitch-db-server.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/openvswitch-db-server.sh
                  - stop
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: openvswitch-bin
              mountPath: /tmp/openvswitch-db-server.sh
              subPath: openvswitch-db-server.sh
              readOnly: true
            - name: run-openvswitch
              mountPath: /run/openvswitch
        - name: openvswitch-vswitchd
{{- if .Values.conf.ovs_dpdk.enabled }}
{{/* Run the container in priviledged mode due to the need for root
permissions when using the uio_pci_generic driver. */}}
{{- $_ := set $envAll.Values.pod.security_context.openvswitch_vswitchd.container.vswitchd "privileged" true -}}
{{/* Limiting CPU cores would severely affect packet throughput
It should be handled through lcore and pmd core masks. */}}
{{- if .Values.pod.resources.enabled }}
{{ $_ := unset $envAll.Values.pod.resources.ovs.vswitchd.requests "cpu" }}
{{ $_ := unset $envAll.Values.pod.resources.ovs.vswitchd.limits "cpu" }}
{{- end }}
{{- end }}
{{ tuple $envAll $openvswitchVswitchdImage | include "helm-toolkit.snippets.image" | indent 10 }}
{{ dict "envAll" $envAll "application" "openvswitch_vswitchd" "container" "vswitchd" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.ovs.vswitchd | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          # ensures this container can speak to the ovs database
          # successfully before its marked as ready
{{ dict "envAll" $envAll "component" "ovs_vswitchd" "container" "ovs_vswitchd" "type" "liveness" "probeTemplate" (include "ovsvswitchlivenessProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
{{ dict "envAll" $envAll "component" "ovs_vswitchd" "container" "ovs_vswitchd" "type" "readiness" "probeTemplate" (include "ovsvswitchreadinessProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
          command:
            - /tmp/openvswitch-vswitchd.sh
            - start
          lifecycle:
            postStart:
              exec:
                command:
                  - /tmp/openvswitch-vswitchd.sh
                  - poststart
            preStop:
              exec:
                command:
                  - /tmp/openvswitch-vswitchd.sh
                  - stop
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: openvswitch-bin
              mountPath: /tmp/openvswitch-vswitchd.sh
              subPath: openvswitch-vswitchd.sh
              readOnly: true
            - name: openvswitch-bin
              mountPath: /tmp/vswitchd_readiness.sh
              subPath: vswitchd_readiness.sh
              readOnly: true
            - name: run
              mountPath: /run
            # NOTE(vsaienko): needed for ovs-tcpdump
            - name: devs
              mountPath: /dev
              mountPropagation: HostToContainer
{{- if .Values.conf.neutron.DEFAULT.support_sync_ovs_info }}
            - name: neutron-sync-state
              mountPath: {{ .Values.conf.neutron.DEFAULT.state_path }}
{{- end }}
{{- if .Values.conf.ovs_dpdk.enabled }}
            - name: hugepages
              mountPath: {{ .Values.conf.ovs_dpdk.hugepages_mountpath | quote }}
            - name: pci-devices
              mountPath: /sys/bus/pci/devices
            - name: huge-pages-kernel
              mountPath: /sys/kernel/mm/hugepages
            - name: node-devices
              mountPath: /sys/devices/system/node
            - name: modules
              mountPath: /lib/modules
            - name: pci-drivers
              mountPath: /sys/bus/pci/drivers
            - name: cgroup
              mountPath: /sys/fs/cgroup
{{- end }}
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: openvswitch-bin
          configMap:
            name: openvswitch-bin
            defaultMode: 365
        - name: run
          hostPath:
            path: /run
            type: Directory
        - name: run-openvswitch
          hostPath:
            path: /run/openvswitch
        - name: host-rootfs
          hostPath:
            path: /
            type: Directory
        - name: devs
          hostPath:
            path: /dev
            type: Directory
{{- if .Values.conf.neutron.DEFAULT.support_sync_ovs_info }}
        - name: neutron-sync-state
          hostPath:
            path: {{ .Values.conf.neutron.DEFAULT.state_path }}
{{- end }}
{{- if .Values.conf.ovs_dpdk.enabled }}
        - name: pci-devices
          hostPath:
            path: /sys/bus/pci/devices
            type: Directory
        - name: huge-pages-kernel
          hostPath:
            path: /sys/kernel/mm/hugepages
            type: Directory
        - name: node-devices
          hostPath:
            path: /sys/devices/system/node
            type: Directory
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: pci-drivers
          hostPath:
            path: /sys/bus/pci/drivers
            type: Directory
        - name: hugepages
          hostPath:
            path: {{ .Values.conf.ovs_dpdk.hugepages_mountpath | quote }}
            type: Directory
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.manifests.daemonset_ovs_vswitchd }}
{{- $envAll := . }}
{{- $daemonset := "openvswitch-vswitchd" }}
{{- $configMapName := "openvswitch-etc" }}
{{- $serviceAccountName := "openvswitch-vswitchd" }}
{{ tuple $envAll "vswitchd" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
{{- $configmap_yaml := "openvswitch.configmap.etc" }}
{{/* Prefer using .Values.overrides rather than .Values.conf.overrides */}}
{{- if index (index .Values "overrides" |default dict ) "openvswitch_openvswitch-vswitchd" }}
{{- list $daemonset "openvswitch.openvswitch-vswitchd.daemonset" $serviceAccountName $configmap_yaml $configMapName "openvswitch.configmap.bin" "openvswitch-bin" . | include "helm-toolkit.utils.daemonset_overrides_root" }}
{{- else }}
{{- $daemonset_yaml := list $daemonset $configMapName $serviceAccountName . | include "openvswitch.openvswitch-vswitchd.daemonset" | toString | fromYaml }}
{{- list $daemonset $daemonset_yaml $configmap_yaml $configMapName . | include "helm-toolkit.utils.daemonset_overrides" }}
{{- end }}
{{- end }}
