{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- define "iscsi.daemonset" }}
{{- $daemonset := index . 0 }}
{{- $configMapName := index . 1 }}
{{- $serviceAccountName := index . 2 }}
{{- $envAll := index . 3 }}
{{- $ssl_enabled := false }}
{{- with $envAll }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iscsi
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{ tuple $envAll .Chart.Name $daemonset | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  selector:
    matchLabels:
{{ tuple $envAll .Chart.Name $daemonset | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll $daemonset | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll .Chart.Name $daemonset | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{- dict "envAll" $envAll "podName" "iscsi-default" "containerNames" (list "iscsi") | include "helm-toolkit.snippets.kubernetes_mandatory_access_control_annotation" | indent 8 }}
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
        configmap-bin-hash: {{ tuple "configmap-bin-iscsi.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc-iscsi.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
{{ dict "envAll" $envAll "application" "iscsi" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      serviceAccountName: {{ $serviceAccountName }}
      nodeSelector:
        {{ .Values.labels.iscsi.node_selector_key }}: {{ .Values.labels.iscsi.node_selector_value }}
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
{{ dict "envAll" $envAll | include "helm-toolkit.snippets.kubernetes_apparmor_loader_init_container" | indent 8 }}
        - name: iscsid-init
{{ tuple $envAll "iscsi_iscsi" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.iscsi | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "iscsi" "container" "iscsid" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          command:
            - /tmp/iscsid-init.sh
          terminationMessagePath: /var/log/termination-log
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: iscsi-bin
              mountPath: /tmp/iscsid-init.sh
              subPath: iscsid-init.sh
              readOnly: true
            - name: etciscsi
              mountPath: /etc/iscsi
              mountPropagation: Bidirectional
            - name: run
              mountPath: /run
            - name: dev
              mountPath: /dev
              mountPropagation: HostToContainer
      containers:
        - name: iscsid
{{ tuple $envAll "iscsi" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.iscsi | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "iscsi" "container" "iscsid" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          command:
            - /tmp/iscsid.sh
          terminationMessagePath: /var/log/termination-log
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: iscsi-bin
              mountPath: /tmp/iscsid.sh
              subPath: iscsid.sh
              readOnly: true
            - name: iscsi-etc
              mountPath: /etc/iscsi/iscsid.conf
              subPath: iscsid.conf
              readOnly: true
            - name: etciscsi
              mountPath: /etc/iscsi
              mountPropagation: Bidirectional
            - name: run
              mountPath: /run
            - name: dev
              mountPath: /dev
              mountPropagation: HostToContainer
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: iscsi-bin
          configMap:
            name: iscsi-bin
            defaultMode: 0555
        - name: iscsi-etc
          secret:
            secretName: {{ $configMapName }}
            defaultMode: 0444
        - name: run
          hostPath:
            path: /run
        - name: etciscsi
          hostPath:
            path: /etc/iscsi
        - name: dev
          hostPath:
            path: /dev
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
{{ dict "envAll" $envAll "component" "iscsi" "requireSys" true | include "helm-toolkit.snippets.kubernetes_apparmor_volumes" | indent 8 }}
{{- end }}
{{- end }}

{{- if .Values.manifests.daemonset_iscsi }}

{{- $envAll := . }}
{{- $daemonset := "iscsi" }}
{{- $configMapName := "iscsi-etc" }}
{{- $serviceAccountName := "iscsi" }}

{{- $dependencyOpts := dict "envAll" $envAll "dependencyMixinParam" "" "dependencyKey" "iscsi" -}}
{{- $_ := include "helm-toolkit.utils.dependency_resolver" $dependencyOpts | toString | fromYaml }}

{{ tuple $envAll "pod_dependency" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
{{- $daemonset_yaml := list $daemonset $configMapName $serviceAccountName . | include "iscsi.daemonset" | toString | fromYaml }}
{{- $configmap_yaml := "iscsi.configmap.etc" }}
{{- list $daemonset "iscsi.daemonset" $serviceAccountName $configmap_yaml $configMapName "iscsi.configmap.bin" "iscsi-bin" . | include "helm-toolkit.utils.daemonset_overrides_root" }}

{{- end }}
