- name: Make lvp chart dependencies
  ansible.builtin.shell:
    cmd: helm dep up
    chdir: "{{ rvl_directory }}/charts/infra/local-volume-provisioner"

- name: Deploy local volume provisioner chart from local path
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: local-volume-provisioner
    chart_ref: "{{ rvl_lvp_local_volume_provisioner_chart }}"
    release_namespace: lvp
    create_namespace: true
    values:
      local_volume_provisioner_mounts: "{{ rvl_lvp_local_volume_provisioner_mounts_image }}"
      local_volume_provisioner: "{{ rvl_lvp_local_volume_provisioner_image }}"
