- name: Template a file to /etc/systemd/network/10-veth-phy-br.netdev
  ansible.builtin.template:
    src: veth.netdev.j2
    dest: /etc/systemd/network/10-veth-phy-br.netdev
    owner: bin
    group: root
    mode: '0644'
  vars:
    veth:
      src: veth-phy
      dst: veth-br

- name: Template a file to /etc/netplan/60-os-floating.yaml
  ansible.builtin.template:
    src: netplan-os-floating.j2
    dest: /etc/netplan/60-os-floating.yaml
    owner: bin
    group: root
    mode: '0644'
  vars:
    veth:
      src: veth-phy
      dst: veth-br
  register: netplan_os_floating

- name: Apply netplan changes
  ansible.builtin.command:  netplan  apply
  when: netplan_os_floating is changed
