- name: Template a file to /etc/systemd/network/10-veth-phy-br.netdev
  ansible.builtin.template:
    src: veth.netdev.j2
    dest: /etc/systemd/network/10-veth-phy-br.netdev
    owner: bin
    group: root
    mode: '0644'
  vars:
    veth:
      src: veth-phy
      dst: veth-br

- name: Template a file to /etc/netplan/60-os-floating.yaml
  ansible.builtin.template:
    src: netplan-os-floating.j2
    dest: /etc/netplan/60-os-floating.yaml
    owner: bin
    group: root
    mode: '0644'
  vars:
    veth:
      src: veth-phy
      dst: veth-br
  register: netplan_os_floating

- name: Apply netplan changes
  ansible.builtin.command:  netplan  apply
  when: netplan_os_floating is changed

- block:
  - name: Make SNAT for public OS network
    ansible.builtin.template:
      src: iptables-public-network.sh.j2
      dest: /etc/networkd-dispatcher/routable.d/iptables-public-network.sh
      owner: root
      group: root
      mode: '0755'

  - name: Apply SNAT rules
    ansible.builtin.command: /etc/networkd-dispatcher/routable.d/iptables-public-network.sh

  when: rvl_network_floating_network_with_snat
