---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
  loop:
    - "{{ rvl_sources_charts }}"

- name: Install local Docker registry as docker container
  ansible.builtin.include_tasks:
    file: "registry/{{ rvl_registry_source }}.yaml"
  when: (rvl_images_base_url != rvl_images_public_base_url) or
        rvl_images_build_loci or
        rvl_images_build_rockoon

- name: Install local HTTPS registry for binary
  ansible.builtin.include_tasks:
    file: "registry/https.yaml"
  when: rvl_binary_base_url != rvl_binary_public_base_url
