{{- if and .Values.manifests.http_route_api }}
{{- $envAll := . -}}
{{- $port := tuple "image" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{- $httpRouteOpts := dict "envAll" $envAll "backendServiceType" "image" "backendService" "api" "backendPort" $port -}}
{{ $httpRouteOpts | include "helm-toolkit.manifests.http_route" }}
{{- end }}
