#!/usr/bin/env python3


OSCTL_COMPONENT_LOGGERS = {
    "cinder": ["cinder", "iscsi"],
    "nova": ["nova", "libvirt"],
    "designate": ["designate", "powerdns"],
    "keystone": ["keystone"],
    "glance": ["glance"],
    "neutron": ["neutron", "openvswitch", "strongswan", "frr"],
    "heat": ["heat"],
    "horizon": ["horizon"],
    "octavia": ["octavia"],
    "barbican": ["barbican"],
    "placement": ["placement"],
    "ironic": ["ironic"],
    "aodh": ["aodh"],
    "panko": ["panko"],
    "ceilometer": ["ceilometer"],
    "gnocchi": ["gnocchi"],
    "tempest": ["tempest"],
    "ceph-rgw": ["ceph-rgw"],
    "masakari": ["masakari"],
    "manila": ["manila"],
    "stepler": ["stepler"],
    # Infra components
    "mariadb": ["mariadb"],
    "memcached": ["memcached"],
    "redis": ["redis"],
    "etcd": ["etcd"],
    "cloudprober": ["cloudprober"],
    "rabbitmq": ["rabbitmq"],
    "openvswitch": ["openvswitch"],
    "libvirt": ["libvirt"],
    "ingress": ["ingress"],
    "frr": ["frr"],
    "iscsi": ["iscsi"],
    "strongswan": ["strongswan"],
    "rockoon": ["rockoon"],
}
