#apiVersion: lcm.mirantis.com/v1alpha1
#kind: HelmBundle

{%- from 'macros/messaging_service_creds.j2' import messaging_service_creds %}
{%- set service = 'heat' %}
{%- set latest_openstack_versions = openstack_versions[openstack_versions.index(spec.openstack_version):] %}
{%- set tungstenfabric_enabled = spec.features.neutron.get('backend', 'ml2') == 'tungstenfabric' %}
{%- set tungstenfabric_custom_api_opts = tf_api_service is defined and tf_api_port is defined %}
{%- set stacklight_enabled = spec.get('features', {}).get('stacklight', {}).get('enabled', False) %}
{%- set notification_topics = ['notifications'] %}
{%- do notification_topics.append('stacklight_notifications') if stacklight_enabled %}
{%- set external_notifications_enabled = spec.get('features', {}).get('messaging', {}).get('notifications', {}).get('external', {}).get('enabled', False) %}
{%- if external_notifications_enabled %}
  {%- for topic in spec.get('features', {}).get('messaging', {}).get('notifications', {}).get('external', {}).get('topics', []) %}
    {%- do notification_topics.append(topic) %}
  {%- endfor %}
{%- endif  %}
{%- set heat_db_cleanup = spec.get('features', {}).get('database', {}).get('cleanup', {}).get('heat', {'enabled': true}) %}
{%- set cadf_audit = spec.get('features', {}).get('logging', {}).get('cadf', {'enabled': false}) %}
{%- set cadf_audit_driver = spec.get('features', {}).get('logging', {}).get('cadf', {}).get('driver', 'messagingv2') %}

spec:
  releases:
{%- if spec.get('migration', {}).get('heat', {}).get('deploy_main_service', True) %}
  - name: openstack-heat
    chart: heat
    values:
      images:
        tags:
{%- for image in [
    "db_drop",
    "image_repo_sync",
    "heat_engine",
    "heat_api",
    "ks_endpoints",
    "db_init",
    "dep_check",
    "heat_engine_cleaner",
    "ks_service",
    "ks_trusts",
    "heat_db_purge",
    "heat_db_sync",
    "bootstrap",
    "rabbit_init",
    "heat_cfn",
    "heat_cloudwatch",
    "test",
    "ks_user",] %}
        {%- if image in images %}
          {{ image }}: {{ images[image] }}
        {%- endif %}
{%- endfor %}
      dependencies:
        static:
          db_init:
            jobs:
              - openstack-mariadb-cluster-wait
{%- if spec.features.network_policies.enabled %}
      network_policy:
{% include 'base/network_policies/orchestration.yaml' %}
{%- endif %}
      manifests:
        cron_job_db_purge: true
        network_policy: {{ spec.features.network_policies.enabled }}
        job_rabbit_init: false
        secret_ca_bundle: true
        job_heat_trusts: false
      conf:
        policy.d:
          01-controller-default.yaml: {{ service_policy }}
          02-custom.yaml: {{ spec.get("features", {}).get("policies", {}).get("heat", {}) }}
        heat:
          DEFAULT:
            server_keystone_endpoint_type: public
          keystone_authtoken:
            memcache_security_strategy: ENCRYPT
            memcache_secret_key: {{ credentials[0].memcached }}
            {%- if OSVer[spec.openstack_version] >= OSVer.train %}
            service_type: orchestration
            {%- endif %}
          clients_swift:
            endpoint_type: public
{%- if cadf_audit.enabled %}
          audit_middleware_notifications:
            driver: {{ cadf_audit_driver }}
{%- else %}
          audit_middleware_notifications:
            driver: noop
{%- endif %}
          oslo_messaging_notifications:
            topics: {{ notification_topics|join(',') }}
{% include 'base/_oslo_policy_enforce_defaults.yaml' %}
        logging:
          logger_heat:
            level: {{ spec.get('features', {}).get('logging', {}).get('heat', {}).get('level', 'INFO') }}
{%- set enabled_plugins = [] %}
{%- if tungstenfabric_enabled %}
  {%- if OSVer[spec.openstack_version] >= OSVer.ussuri %}
    {%- do enabled_plugins.append('vnc_api/gen/heat') %}
  {%- endif %}
{%- endif %}
{%- if spec.features.neutron.get('bgpvpn', {}).get('enabled') %}
  {%- do enabled_plugins.append('networking_bgpvpn_heat') %}
{%- endif %}
{%- if enabled_plugins %}
        plugins: {{ enabled_plugins }}
{%- endif %}
      network:
{%- set core_plugin = spec.features.neutron.get('backend', 'ml2')%}
{%- if core_plugin == "ml2/ovn" %}
{%- set core_plugin = "ml2" %}
{%- endif %}
        core_plugin: {{ core_plugin }}
      endpoints:
        cluster_domain_suffix: {{ spec.internal_domain_name }}
{% include 'base/_admin_identity.yaml' %}
{% include 'base/_cache.yaml' %}
        oslo_db:
          auth:
            admin:
              username: {{ admin_creds.database.username }}
              password: {{ admin_creds.database.password }}
            heat:
              username: {{ credentials[0].database.user.username }}
              password: {{ credentials[0].database.user.password }}
{% include 'base/_messaging_shared.yaml' %}
{% include 'base/_notifications.yaml' %}
        orchestration:
          host_fqdn_override:
            public:
              host: heat.{{ spec.public_domain_name }}
              tls:
                ca: |
{{ spec.features.ssl.public_endpoints.ca_cert | indent( width=18, first=True) }}
{%- if proxy_settings is defined %}
{%- if proxy_settings.get("proxy_ca_certificate") %}
{{ proxy_settings["proxy_ca_certificate"] | indent( width=18, first=True) }}
{%- endif %}
{%- endif %}
                crt: |
{{ spec.features.ssl.public_endpoints.api_cert | indent( width=18, first=True) }}
                key: |
{{ spec.features.ssl.public_endpoints.api_key | indent( width=18, first=True) }}
          hosts:
            admin:
              host: heat-api
            default: heat
            internal: heat-api
            public:
              host: heat
              tls:
                ca: |
{{ spec.features.ssl.public_endpoints.ca_cert | indent( width=18, first=True) }}
                crt: |
{{ spec.features.ssl.public_endpoints.api_cert | indent( width=18, first=True) }}
                key: |
{{ spec.features.ssl.public_endpoints.api_key | indent( width=18, first=True) }}
          port:
            api:
              admin: 8004
              default: 80
              internal: 8004
              public: 443
          scheme:
            default: http
            public: https
        cloudformation:
          host_fqdn_override:
            public:
              host: cloudformation.{{ spec.public_domain_name }}
              tls:
                ca: |
{{ spec.features.ssl.public_endpoints.ca_cert | indent( width=18, first=True) }}
                crt: |
{{ spec.features.ssl.public_endpoints.api_cert | indent( width=18, first=True) }}
                key: |
{{ spec.features.ssl.public_endpoints.api_key | indent( width=18, first=True) }}
          hosts:
            admin:
              host: heat-cfn
            default: cloudformation
            internal: heat-cfn
            public:
              host: cloudformation
              tls:
                ca: |
{{ spec.features.ssl.public_endpoints.ca_cert | indent( width=18, first=True) }}
                crt: |
{{ spec.features.ssl.public_endpoints.api_cert | indent( width=18, first=True) }}
                key: |
{{ spec.features.ssl.public_endpoints.api_key | indent( width=18, first=True) }}
          port:
            api:
              admin: 8000
              default: 80
              internal: 8000
              public: 443
          scheme:
            default: http
            public: https
      {%- if tungstenfabric_enabled and tungstenfabric_custom_api_opts %}
        tungstenfabric:
          host_fqdn_override:
            public:
              host: {{ tf_api_service }}.{{ spec.public_domain_name }}
              tls:
                ca: |
{{ spec.features.ssl.public_endpoints.ca_cert | indent( width=18, first=True) }}
                crt: |
{{ spec.features.ssl.public_endpoints.api_cert | indent( width=18, first=True) }}
                key: |
{{ spec.features.ssl.public_endpoints.api_key | indent( width=18, first=True) }}
          hosts:
            default: {{ tf_api_service }}
            public:
              host: {{ tf_api_service }}
              tls:
                ca: |
{{ spec.features.ssl.public_endpoints.ca_cert | indent( width=18, first=True) }}
                crt: |
{{ spec.features.ssl.public_endpoints.api_cert | indent( width=18, first=True) }}
                key: |
{{ spec.features.ssl.public_endpoints.api_key | indent( width=18, first=True) }}
          port:
            api:
              default: {{ tf_api_port }}
              public: 443
          scheme:
            default: http
            public: https
      {%- endif %}
      jobs:
{% include 'base/_ks_jobs.yaml' %}
        db_purge:
          enabled: {{ heat_db_cleanup.enabled }}
          cron: {{ heat_db_cleanup.get("schedule", "1 5 * * 1") }}
          script:
            config:
              age: {{ heat_db_cleanup.get("age", 30) }}
              batch_size: {{ heat_db_cleanup.get("batch", 10) }}
{%- endif %}
