{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- define "gnocchiProbeTemplate" }}
exec:
  command:
    - "true"
{{- end }}

{{- if .Values.manifests.daemonset_metricd }}
{{- $envAll := . }}

{{- $storageDriver := .Values.conf.gnocchi.storage.driver }}

{{- $mounts_gnocchi_metricd := .Values.pod.mounts.gnocchi_metricd.gnocchi_metricd }}
{{- $mounts_gnocchi_metricd_init := .Values.pod.mounts.gnocchi_metricd.init_container }}

{{- $serviceAccountName := "gnocchi-metricd" }}
{{ tuple $envAll "metricd" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gnocchi-metricd
  labels:
{{ tuple $envAll "gnocchi" "metricd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  selector:
    matchLabels:
{{ tuple $envAll "gnocchi" "metricd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll "metricd" | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "gnocchi" "metricd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
{{ dict "envAll" $envAll "application" "gnocchi_metricd" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      nodeSelector:
        {{ .Values.labels.metricd.node_selector_key }}: {{ .Values.labels.metricd.node_selector_value }}
      initContainers:
{{ tuple $envAll "metricd" $mounts_gnocchi_metricd_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: gnocchi-metricd
{{ tuple $envAll "gnocchi_metricd" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.metricd | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "gnocchi_metricd" "container" "gnocchi_metricd" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
{{ dict "envAll" $envAll "component" "metricd" "container" "metricd" "type" "liveness" "probeTemplate" (include "gnocchiProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
{{ dict "envAll" $envAll "component" "metricd" "container" "metricd" "type" "readiness" "probeTemplate" (include "gnocchiProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
          command:
            - /tmp/gnocchi-metricd.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-etc-gnocchi
              mountPath: /etc/gnocchi
            - name: gnocchi-etc
              mountPath: /etc/gnocchi/gnocchi.conf
              subPath: gnocchi.conf
              readOnly: true
            - name: gnocchi-oslo-policy
              mountPath: /etc/gnocchi/policy.d/
            - name: gnocchi-bin
              mountPath: /tmp/gnocchi-metricd.sh
              subPath: gnocchi-metricd.sh
              readOnly: true
            - name: gnocchi-bin
              mountPath: /tmp/health-probe-metricd.py
              subPath: health-probe-metricd.py
              readOnly: true
{{- if eq $storageDriver "ceph" }}
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            {{ dict "envAll" $envAll "objectType" "mountpoint" "application" "gnocchi" | include "helm-toolkit.snippets.kubernetes_ceph_keyring_objects" | indent 12 }}
{{- end }}
{{ if $mounts_gnocchi_metricd.volumeMounts }}{{ toYaml $mounts_gnocchi_metricd.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: pod-etc-gnocchi
          emptyDir: {}
        - name: gnocchi-etc
          secret:
            secretName: gnocchi-etc
            defaultMode: 416
        - name: gnocchi-bin
          configMap:
            name: gnocchi-bin
            defaultMode: 504
        - name: gnocchi-oslo-policy
          secret:
            secretName: gnocchi-oslo-policy
            defaultMode: 416
{{- if eq $storageDriver "ceph" }}
        - name: ceph-etc
          configMap:
            name: {{ .Values.ceph_client.configmap }}
{{- end }}
{{ if $mounts_gnocchi_metricd.volumes }}{{ toYaml $mounts_gnocchi_metricd.volumes | indent 8 }}{{ end }}
{{- end }}
