images:
  tags:
    envoy: mirantis.azurecr.io/openstack/extra/envoy:1.37.1-noble-20260323165333
  pull_policy: "IfNotPresent"
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

endpoints:
  cluster_domain_suffix: cluster.local
  app_gateway:
    hosts:
      default:
        host: app-gateway
    port:
      https:
        default: 10443
        public: 443
    host_fqdn_override:
      public: null

labels:
  proxy:
    node_selector_key: kubernetes.io/os
    node_selector_value: linux

gateways:
  default: {}
    # The Gateway object spec is formed as follows:
    # 1. listeners dict is converted to Gateway API expected list
    #    of listeners where key in dict is name of listener.
    #    List of listeners is formed in alfanumeric order. Optional
    #    flag enabled can be used to disable listener
    # Example dict:
    # listeners:
    #   https1:
    #     allowedRoutes:
    #       namespaces:
    #         from: All
    #     port: 444
    #     protocol: HTTPS
    # Resulting list:
    # listeners:
    #   - allowedRoutes:
    #       namespaces:
    #         from: All
    #     name: https1
    #     port: 444
    #     protocol: HTTPS
    # 2. All other options are translated as is.
gateway_classes:
  default: {}
envoy_proxies:
  default: {}
policies:
  backend_traffic:
    default:
      retry:
        numRetries: 3
        retryOn:
          triggers:
          - connect-failure
          - refused-stream
          - unavailable
          - cancelled
          - retriable-status-codes
          # Safe reset retry
          - reset-before-request
      timeout:
        http:
          requestTimeout: 60s
          connectionIdleTimeout: 60s

secrets:
  tls:
    app_gateway:
      https:
        public: app-gateway-https-certs

network_policy: {}

manifests:
  gateway: true
  gateway_class: true
  envoy_proxy: true
  secret_tls: true
  backend_traffic_policy: true
  network_policy: false
