{{- if and .Values.admission.enabled .Values.admission.network_policy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: rockoon-admission-netpol-{{ .Values.osdpl.namespace }}
spec:
  ingress:
  - from:
{{- range .Values.global.podNetworks }}
    - ipBlock:
        cidr: {{ .cidr }}
{{- end }}
    # NOTE(vsaienko): for combined CP case when kubeapi reach admission running on
    # local node PRODX-39369
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: {{ .Values.admission.settings.raw.OSCTL_ADMISSION_BIND_PORT }}
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.osdpl.settings.raw.OSCTL_LMA_DEPLOYMENT_NAMESPACE | default "stacklight" }}
    ports:
    - port: {{ .Values.admission.settings.raw.OSCTL_ADMISSION_BIND_PORT }}
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rockoon.fullname" . }}-admission
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
{{- end }}