{{- if .Values.admission.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: rockoon-admission-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rockoon-admission-role-cluster
rules:
  # Application: read-only access for watching cluster-wide.
  - apiGroups: [lcm.mirantis.com]
    resources: [openstackdeploymentstatus]
    verbs: [list, get, watch]
  - apiGroups: [lcm.mirantis.com]
    resources: [openstackdeployments]
    verbs: [list, get, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "{{ .Values.osdpl.namespace }}"
  name: "rockoon-admission-role-{{ .Values.osdpl.namespace }}"
rules:
  # Application: read secret for substitution
  - apiGroups: [""]
    resources: [secrets]
    verbs: [list, get, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rockoon-admission-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rockoon-admission-role-cluster
subjects:
  - kind: ServiceAccount
    name: rockoon-admission-account
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{{ .Values.osdpl.namespace }}"
  name: "rockoon-admission-rolebinding-{{ .Values.osdpl.namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "rockoon-admission-role-{{ .Values.osdpl.namespace }}"
subjects:
  - kind: ServiceAccount
    name: rockoon-admission-account
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rockoon.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "rockoon.fullname" . }}-admission
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rockoon.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.admission.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rockoon.fullname" . }}-admission
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rockoon.fullname" . }}-admission
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        admission-tls-hash: {{ tuple "admission-controller-tls-secret.yaml" . | include "rockoon.utils.hash" }}
    spec:
      serviceAccountName: rockoon-admission-account
      securityContext:
        {{- toYaml .Values.admission.pod.controller.security_context | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.admission.pod.controller.admission.security_context | nindent 12 }}
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - uwsgi
            - /opt/operator/uwsgi.ini
          ports:
            - name: https
              containerPort: {{ .Values.admission.settings.raw.OSCTL_ADMISSION_BIND_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/opt/operator/certs"
              name: {{ include "rockoon.fullname" . }}-admission-tls
              readOnly: true
      volumes:
        - name: {{ include "rockoon.fullname" . }}-admission-tls
          secret:
            secretName: {{ include "rockoon.fullname" . }}-admission-tls
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
