{{- if and .Values.exporter.enabled .Values.exporter.network_policy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: rockoon-exporter-netpol-{{ .Values.osdpl.namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.osdpl.settings.raw.OSCTL_LMA_DEPLOYMENT_NAMESPACE | default "stacklight" }}
    ports:
    - port: {{ .Values.exporter.settings.raw.OSCTL_EXPORTER_BIND_PORT }}
      protocol: TCP
  podSelector:
    matchLabels:
      application: rockoon
      component: exporter
  policyTypes:
  - Ingress
{{- end }}