---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rockoon.fullname" . }}-resources
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rockoon.fullname" . }}-resources
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
rules:
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, create, patch, delete]
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [get, create, patch]
  - apiGroups: [zalando.org]
    resources: [kopfpeerings]
    verbs: [get, create, patch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "rockoon.fullname" . }}-resources
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, create]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rockoon.fullname" . }}-resources
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rockoon.fullname" . }}-resources
subjects:
  - kind: ServiceAccount
    name: {{ include "rockoon.fullname" . }}-resources
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "rockoon.fullname" . }}-resources
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rockoon.fullname" . }}-resources
subjects:
  - kind: ServiceAccount
    name: {{ include "rockoon.fullname" . }}-resources
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: {{ include "rockoon.name" . }}
    helm.sh/chart: {{ include "rockoon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  name: {{ include "rockoon.name" . }}-ensure-resources
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      serviceAccountName: {{ include "rockoon.fullname" . }}-resources
      restartPolicy: OnFailure
      securityContext:
        {{- toYaml .Values.osdpl.pod.ensure_resources.security_context | nindent 8 }}
      containers:
      - name: main
        command:
          - osctl-ensure-shared-resources
        image: {{ tuple . .Values.image | include "getImageUrl" }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/resources
          name: deploy-resources-bin
          readOnly: true
        securityContext:
          {{- toYaml .Values.osdpl.pod.ensure_resources.ensure_resources.security_context | nindent 10 }}
      volumes:
      - name: deploy-resources-bin
        configMap:
          name: {{ include "rockoon.name" . }}-deploy-resources-bin
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
