{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.job_manage_networks }}
{{- $envAll := . }}

{{- $serviceAccountName := "ironic-manage-networks" }}
{{ tuple $envAll "manage_networks" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ironic-manage-networks
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
spec:
  backoffLimit: 20
  template:
    metadata:
      labels:
{{ tuple $envAll "ironic" "manage-networks" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.job.node_selector_key }}: {{ .Values.labels.job.node_selector_value }}
{{ dict "envAll" $envAll "application" "manage_networks" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      initContainers:
        {{ tuple $envAll "manage_networks" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container"  | indent 8 }}
      containers:
        - name: ironic-manage-networks
{{ tuple $envAll "ironic_manage_networks" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.jobs.manage_networks | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "manage_networks" "container" "manage_networks" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          env:
{{- include "helm-toolkit.snippets.keystone_os_cloud_vars" ( dict "osCloudName" "ironic" ) | indent 12 }}
          command:
            - /tmp/manage-networks.py
            - --resources-file
            - /tmp/networks-data.yaml
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: ironic-bin
              mountPath: /tmp/manage-networks.py
              subPath: manage-networks.py
              readOnly: true
            - name: ironic-bin
              mountPath: /tmp/networks-data.yaml
              subPath: networks-data.yaml
              readOnly: true
            - name: os-clouds
              mountPath: /etc/openstack/clouds.yaml
              subPath: clouds.yaml
              readOnly: true
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: ironic-bin
          configMap:
            name: ironic-bin
            defaultMode: 504
        - name: os-clouds
          secret:
            secretName: {{ .Chart.Name }}-os-clouds
            defaultMode: 416
{{- end }}
