parameters:
  octavia:
    api:
      database:
        host: ${_param:mcp2_database_octavia_address}
        password: ${_param:mcp2_database_octavia_password}
        user: ${_param:mcp2_database_octavia_username}
