parameters:
  cinder:
    controller:
      database:
        host: ${_param:mcp2_database_cinder_address}
        password: ${_param:mcp2_database_cinder_password}
        user: ${_param:mcp2_database_cinder_username}
