{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.cron_job_placement_audit }}
{{- $envAll := . }}

{{- $serviceAccountName := "nova-placement-audit-cron" }}
{{ tuple $envAll "placement_audit" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nova-placement-audit
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
spec:
  schedule: {{ .Values.jobs.placement_audit.cron | quote }}
  successfulJobsHistoryLimit: {{ .Values.jobs.placement_audit.history.success }}
  suspend: {{ .Values.jobs.placement_audit.suspend }}
  failedJobsHistoryLimit: {{ .Values.jobs.placement_audit.history.failed }}
  {{- if .Values.jobs.placement_audit.starting_deadline }}
  startingDeadlineSeconds: {{ .Values.jobs.placement_audit.starting_deadline }}
  {{- end }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
{{ tuple $envAll "nova" "placement-audit" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      backoffLimit: {{ .Values.jobs.placement_audit.backoff_limit }}
      template:
        metadata:
          labels:
{{ tuple $envAll "nova" "placement-audit" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 12 }}
        spec:
          serviceAccountName: {{ $serviceAccountName }}
{{ dict "envAll" $envAll "application" "placement_audit" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 10 }}
          restartPolicy: {{ .Values.jobs.placement_audit.restart_policy }}
          nodeSelector:
            {{ .Values.labels.job.node_selector_key }}: {{ .Values.labels.job.node_selector_value }}
          initContainers:
{{ tuple $envAll "placement_audit" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 12 }}
          containers:
            - name: placement-audit
{{ tuple $envAll "nova_placement_audit" | include "helm-toolkit.snippets.image" | indent 14 }}
{{ tuple $envAll $envAll.Values.pod.resources.jobs.placement_audit | include "helm-toolkit.snippets.kubernetes_resources" | indent 14 }}
{{ dict "envAll" $envAll "application" "placement_audit" "container" "placement_audit" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 14 }}
              command:
                - /tmp/placement-audit.sh
              volumeMounts:
                - name: pod-tmp
                  mountPath: /tmp
                - name: nova-bin
                  mountPath: /tmp/placement-audit.sh
                  subPath: placement-audit.sh
                  readOnly: true
                - name: etcnova
                  mountPath: /etc/nova
                - name: nova-etc
                  mountPath: /etc/nova/nova.conf
                  subPath: nova.conf
                  readOnly: true
                {{- if .Values.conf.nova.DEFAULT.log_config_append }}
                - name: nova-etc
                  mountPath: {{ .Values.conf.nova.DEFAULT.log_config_append }}
                  subPath: {{ base .Values.conf.nova.DEFAULT.log_config_append }}
                  readOnly: true
                {{- end }}
            - name: placement-audit-report
{{ tuple $envAll "nova_placement_audit" | include "helm-toolkit.snippets.image" | indent 14 }}
{{ tuple $envAll $envAll.Values.pod.resources.jobs.placement_audit | include "helm-toolkit.snippets.kubernetes_resources" | indent 14 }}
{{ dict "envAll" $envAll "application" "placement_audit" "container" "placement_audit_report" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 14 }}
              command:
                - /tmp/placement-audit-report.py
              volumeMounts:
                - name: pod-tmp
                  mountPath: /tmp
                - name: nova-bin
                  mountPath: /tmp/placement-audit-report.py
                  subPath: placement-audit-report.py
                  readOnly: true
{{- dict "enabled" .Values.manifests.certificates "name" .Values.endpoints.oslo_db.auth.admin.secret.tls.internal "path" "/etc/mysql/certs" | include "helm-toolkit.snippets.tls_volume_mount" | indent 16 }}
          volumes:
            - name: pod-tmp
              emptyDir: {}
            - name: etcnova
              emptyDir: {}
            - name: nova-etc
              secret:
                secretName: nova-etc
                defaultMode: 416
            - name: nova-bin
              configMap:
                name: nova-bin-aux
                defaultMode: 504
{{- dict "enabled" .Values.manifests.certificates "name" .Values.endpoints.oslo_db.auth.admin.secret.tls.internal | include "helm-toolkit.snippets.tls_volume" | indent 12 }}
{{- end }}
