parameters:
  designate:
    server:
      database:
        host: ${_param:mcp2_database_designate_address}
        password: ${_param:mcp2_database_designate_password}
        user: ${_param:mcp2_database_designate_username}
