{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- define "ag.default_gateway" }}
gatewayClassName: {{ .Release.Namespace }}-gatewayclass
infrastructure:
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ .Release.Namespace }}-envoy-proxy-config
{{- end -}}

{{- define "ag.default_listeners" }}
https:
  allowedRoutes:
    namespaces:
      from: All
  port: {{ tuple "app_gateway" "public" "https" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
  protocol: HTTPS
  tls:
    certificateRefs:
    - group: ""
      kind: Secret
      name: {{ index .Values.secrets "tls" "app_gateway" "https" "public" }}
    mode: Terminate
{{- end }}

{{- define "ag.to_listeners_list" }}
{{- $list_items := list }}
{{- $dict_items := . }}
{{- range $name := sortAlpha (keys $dict_items) }}
  {{- $f := deepCopy (index $dict_items $name) }}
  {{- $_ := set $f "name" $name }}
  {{- if dig "enabled" true $f }}
    {{- $_ := unset $f "enabled" }}
    {{- $list_items = append $list_items $f }}
  {{- end }}
{{- end }}
{{- if $list_items }}
{{ toYaml $list_items }}
{{- end }}
{{- end }}

{{- if .Values.manifests.gateway }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ tuple "app_gateway" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
{{- $gateway := include "ag.default_gateway" . | fromYaml }}
{{- $listeners := include "ag.default_listeners" . | fromYaml }}
{{- $user_gateway := deepCopy .Values.gateways.default }}
{{- $user_listeners := index $user_gateway "listeners" }}
{{- $_ := unset $user_gateway "listeners" }}
{{- $merged_listeners := merge $user_listeners $listeners | include "ag.to_listeners_list" }}
{{- $mergedGateway := merge $user_gateway $gateway }}
{{ toYaml $mergedGateway | indent 2 }}
  listeners:
{{- $merged_listeners | indent 4 -}}
{{- end -}}
