{{- if and .Values.manifests.http_route_api }}
{{- $envAll := . -}}
{{- $port := tuple "dashboard" "internal" "web" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{- $httpRouteOpts := dict "envAll" $envAll "backendServiceType" "dashboard" "backendService" "dashboard" "backendPort" $port -}}
{{ $httpRouteOpts | include "helm-toolkit.manifests.http_route" }}
{{- end }}
