all:
  vars:
    ansible_ssh_user: ubuntu
    k0s_worker_on_controller: true
    k0s_no_taints: true
    k0s_version: 1.31.8+k0s.0
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    kubeconfig: "{{ inventory_dir }}/artifacts/k0s-kubeconfig.yml"
    rvl_images_build_rockoon: false
    rvl_images_build_loci: false
    rvl_registry_source: systemd
    rvl_registry_binary_mode: proxy
    rvl_registry_docker_mode: proxy
    rvl_images_public_base_url: mirantis.azurecr.io
    rvl_binary_public_base_url: https://binary.mirantis.com
    rvl_images_build_tag: 1.1.7
    rvl_images_base_url: "{{ rvl_registry_host }}"
    rvl_binary_base_url: "{{ rvl_registry_binary_url }}"
    rvl_chart_ref_rockoon: "{{ rvl_registry_binary_url }}/openstack/helm/rockoon/rockoon-{{ rvl_images_build_tag }}.tgz"
    rvl_openvpn_enable: true

  hosts:
    oc-virtual-lab-server-ctl-01:
      ansible_host: localhost
      ansible_connection: local

  children:
    computes:
      hosts:
        oc-virtual-lab-server-ctl-01:
    controllers:
      hosts:
        oc-virtual-lab-server-ctl-01:
    k8s_controllers:
      hosts:
        oc-virtual-lab-server-ctl-01:
    k8s_workers:
      hosts:
