{{- if .Values.network_policy.rfo.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: rfo-netpol
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.stacklight_namespace }}
    ports:
    - port: 9710
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: os-redis-operator
      app.kubernetes.io/name: redis-operator
  policyTypes:
  - Ingress
{{- end }}
