{{- if .Values.network_policy.rfr.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: "rfr-netpol"
spec:
  ingress:
    - from:
      {{- range $podNet := .Values.global.podNetworks }}
      - ipBlock:
         cidr: {{ $podNet.cidr }}
      {{- end }}
      - namespaceSelector:
          matchLabels:
             kubernetes.io/metadata.name: {{ .Values.osdpl_namespace }}
      ports:
      - port: 6379
        protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/managed-by: redis-operator
      app.kubernetes.io/part-of: redis-failover
  policyTypes:
  - Ingress
{{- end }}
