parameters:
  heat:
    server:
      database:
        host: ${_param:mcp2_database_heat_address}
        password: ${_param:mcp2_database_heat_password}
        user: ${_param:mcp2_database_heat_username}
