{{- if and .Values.manifests.http_route_server }}
{{- $envAll := . -}}
{{- $port := tuple "network" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{- $httpRouteOpts := dict "envAll" $envAll "backendServiceType" "network" "backendService" "server" "backendPort" $port -}}
{{ $httpRouteOpts | include "helm-toolkit.manifests.http_route" }}
{{- end }}
